const plural = (n: number, word: string) => `${n} ${word}${n === 1 ? "" : "s"}`;

export const text = {
  appName: "WP",
  loading: "Loading",
  storageFailed: "This phone could not keep your change. Free some space or allow site data, then try again.",
  storageBroken: "This browser blocked local storage, so WP cannot start. Allow site data for this page and reload.",
  notFound: "Nothing here",
  crashed: "Something went wrong and this screen could not be shown. Your data on this phone is untouched.",
  reload: "Reload",
  resetView: "Reset the view",
  gone: "This item was deleted",
  undo: "Undo",
  back: "Back",
  save: "Save",
  saved: "Saved",
  cancel: "Cancel",
  delete: "Delete",
  add: "Add",
  notSet: "Not set",
  nobody: "Nobody yet",
  both: "Both",
  you: "You",
  them: "Them",
  takeIt: "I'll take it",
  call: "Call",
  whatsapp: "WhatsApp",
  due: "Due",
  paidOn: "Paid",
  noDueDate: "No due date",
  markPaid: "Mark paid",
  markUnpaid: "Undo",
  amountHint: "Whole rupiah. Leave empty if not set yet.",
  people: (n: number) => (n === 1 ? "1 person" : `${n} people`),
  reopen: (title: string) => `Mark ${title} as not done`,
  complete: (title: string) => `Mark ${title} as done`,
  nav: {
    label: "Main",
    week: "This week",
    tasks: "Tasks",
    budget: "Budget",
    vendors: "Vendors",
    guests: "Guests",
    settings: "Settings",
  },
  field: {
    common: {
      title: "Name",
      status: "Status",
      due_on: "Due date",
      who: "Owner",
      group_key: "Group",
      amount: "Amount",
      qty: "Quantity",
      note: "Note",
      "data.phone": "Phone",
      "data.pic": "Contact person",
      "data.contract_url": "Contract link",
      "data.facts": "Key facts",
      "data.decision": "Needs a decision",
      "data.proof_url": "Proof link",
    },
    task: { group_key: "Phase" },
    vendor: { group_key: "Category", amount: "Quoted price" },
    guest: { who: "Side", group_key: "Category", qty: "People" },
    planned: { group_key: "Event", amount: "Planned amount" },
    payment: { who: "Paid by" },
  },
  option: {
    status: {
      todo: "To do",
      done: "Done",
      option: "Option",
      confirmed: "Confirmed",
      cancelled: "Cancelled",
      sent: "Invited",
      declined: "Declined",
      due: "Due",
      paid: "Paid",
    },
    "guest.status": { todo: "Not invited yet", sent: "Invited", confirmed: "Confirmed", declined: "Declined" },
  },
  event: {
    engagement: "Engagement",
    ceremony: "Ceremony (akad)",
    reception: "Reception",
  },
  invalid: {
    phone: "Enter a phone number such as 0812 3456 7890 or +62 812 3456 7890.",
    int: "Enter a whole number, for example 2500000 or 2.500.000.",
  },
  quickAdd: {
    task: { label: "New task", placeholder: "Add a task" },
    vendor: { label: "New vendor", placeholder: "Add a vendor" },
    guest: { label: "New guest", placeholder: "Add a guest" },
    side: "Side",
  },
  countdown: {
    unset: "Set the akad date",
    days: (n: number) =>
      n > 0 ? `${plural(n, "day")} to the akad` : n === 0 ? "The akad is today" : `${plural(-n, "day")} since the akad`,
  },
  week: {
    empty: "Nothing is due in the next 7 days.",
    overdue: "Overdue",
    soon: "Next 7 days",
    undated: "No date",
  },
  empty: {
    task: "No tasks yet. Add the first one above.",
    vendor: "No vendors yet.",
    guest: "No guests yet.",
    budget: "No budget lines yet. Add the first one above.",
    payments: "No payments yet.",
  },
  budget: {
    planned: "Planned",
    paid: "Paid",
    remaining: "Remaining",
    over: "Over budget",
    progress: "Paid of planned",
    paidNoEstimate: "Paid, no estimate",
    unestimated: (n: number) => `${plural(n, "line")} without an estimate`,
    addLabel: "New budget line",
    addPlaceholder: "Add a budget line",
    event: "Event",
    amountLabel: "Amount in rupiah",
    amountPlaceholder: "Amount",
    paidAmount: (amount: string) => `${amount} paid`,
    overBy: (amount: string) => `${amount} over`,
    left: (amount: string) => `${amount} left`,
    payments: "Payments",
    addPayment: "Add a payment",
    paymentLabel: "Label (optional)",
  },
  notice: {
    reset: "The data on the server was reset, so this phone was reset to match.",
    discarded: (n: number) => `${plural(n, "change")} made on this phone could not be kept.`,
    dismiss: "Dismiss",
  },
  sync: {
    title: "Sync",
    synced: "Up to date",
    storage: "Not saved on this phone",
    storageBody: "This phone could not store your latest change, so it was not kept. Free some space or allow site data for this page, then enter it again.",
    unknownRow: "A row that is no longer here",
    cleared: "cleared",
    yes: "yes",
    pending: (n: number) => `${n} waiting to sync`,
    offline: (n: number) => (n > 0 ? `Offline · ${n} waiting` : "Offline"),
    rejected: (n: number) => `${n} need attention`,
    login: "Log in again",
    onlineBody: "Connected. Changes are sent as soon as you make them.",
    offlineBody: "The server cannot be reached. Everything you enter is saved on this phone and sent later.",
    expiredBody: "Your login expired. Log in again to send your changes. Nothing is lost.",
    waiting: (n: number) => (n === 0 ? "Nothing waiting to sync." : `${n} ${n === 1 ? "change is" : "changes are"} waiting to sync.`),
    now: "Sync now",
    attention: "Needs attention",
    attentionBody: "The server refused these changes. They are not applied. Discard them and enter them again if you still need them.",
    discard: "Discard",
    op: { create: "New", update: "Change to", delete: "Delete" },
    table: { items: "item", budget_entries: "budget entry", settings: "setting" },
  },
  settings: {
    ceremonyDate: "Akad date (marriage contract ceremony)",
    timezone: "Time zone",
    zoneUnsupported: "This phone does not support the saved time zone, so dates use the default zone. You can still edit it.",
    yourNickname: "Your nickname",
    theirNickname: "Their nickname",
    signedInAs: (name: string) => `You are signed in as ${name}.`,
    export: "Export",
    exportAll: "Everything (JSON)",
    syncDetails: "Sync details",
  },
  export: {
    task: "Tasks (CSV)",
    vendor: "Vendors (CSV)",
    guest: "Guests (CSV)",
    planned: "Budget lines (CSV)",
    payment: "Payments (CSV)",
  },
  connect: {
    title: "Can't reach the server yet",
    body: "This phone has not loaded your plan yet. Check your connection and try again. Nothing is created until the plan has loaded once.",
    retry: "Try again",
  },
};
