const plural = (n: number, word: string) => `${n} ${word}${n === 1 ? "" : "s"}`;

export const text = {
  appName: "WP",
  loading: "Loading",
  storageFailed: "This phone could not keep your change. Free some space or allow site data, then try again.",
  storageBrokenTitle: "Storage is blocked",
  storageBroken: "This browser blocked local storage, so WP cannot start. Allow site data for this page and reload.",
  notFound: "Nothing here",
  crashedTitle: "Something went wrong",
  crashed: "This screen could not be shown. Your data on this phone is untouched.",
  reload: "Reload",
  resetView: "Reset the view",
  gone: "This item was deleted",
  undo: "Undo",
  back: "Back",
  save: "Save",
  saved: "Saved",
  cancel: "Cancel",
  delete: "Delete",
  add: "Add",
  notSet: "Not set",
  nobody: "Nobody yet",
  both: "Both",
  you: "You",
  them: "Them",
  takeIt: "Take it",
  takeNamed: (title: string) => `Take it: ${title}`,
  markPaidNamed: (title: string) => `Mark paid: ${title}`,
  markUnpaidNamed: (title: string) => `Undo paid: ${title}`,
  doneOn: "Done",
  call: "Call",
  whatsapp: "WhatsApp",
  callNamed: (title: string) => `Call ${title}`,
  whatsappNamed: (title: string) => `WhatsApp ${title}`,
  noNumber: "No number",
  due: "Due",
  paidOn: "Paid",
  noDueDate: "No due date",
  markPaid: "Mark paid",
  markUnpaid: "Undo",
  amountHint: "Whole rupiah. Leave empty if not set yet.",
  people: (n: number) => (n === 1 ? "1 person" : `${n} people`),
  reopen: (title: string) => `Mark ${title} as not done`,
  complete: (title: string) => `Mark ${title} as done`,
  tasks: "Tasks",
  nav: {
    label: "Main",
    home: "Home",
    money: "Money",
    people: "People",
    settings: "Settings",
  },
  owner: {
    label: "Show",
    everyone: "Everyone",
    mine: "Mine",
    empty: "Nothing here for this filter.",
  },
  field: {
    common: {
      title: "Name",
      status: "Status",
      due_on: "Due date",
      who: "Owner",
      group_key: "Group",
      amount: "Amount",
      qty: "Quantity",
      note: "Note",
      "data.phone": "Phone",
      "data.pic": "Contact person",
      "data.contract_url": "Contract link",
      "data.facts": "Key facts",
      "data.decision": "Needs a decision",
      "data.proof_url": "Proof link",
    },
    task: { group_key: "Phase" },
    vendor: { group_key: "Category", amount: "Quoted price" },
    guest: { who: "Side", group_key: "Category", qty: "People" },
    planned: { group_key: "Event", amount: "Planned amount" },
    payment: { who: "Paid by" },
  },
  option: {
    status: {
      todo: "To do",
      done: "Done",
      option: "Option",
      confirmed: "Confirmed",
      cancelled: "Cancelled",
      sent: "Invited",
      declined: "Declined",
      due: "Due",
      paid: "Paid",
    },
    "guest.status": { todo: "Not invited yet", sent: "Invited", confirmed: "Coming", declined: "Not coming" },
    "vendor.status": { option: "Considering", confirmed: "Booked", cancelled: "Dropped" },
  },
  event: {
    engagement: "Engagement",
    ceremony: "Ceremony (akad)",
    reception: "Reception",
  },
  invalid: {
    phone: "Enter a phone number such as 0812 3456 7890 or +62 812 3456 7890.",
    int: "Enter a whole number, for example 2500000 or 2.500.000.",
    url: "Enter a link that starts with http:// or https://.",
    text: "Use at most 500 characters, with at least one that shows.",
    longtext: "Use at most 2,000 characters, with at least one that shows.",
    note: "Use at most 10,000 characters.",
    date: "Pick a date.",
    required: "Add a name.",
  },
  quickAdd: {
    task: { label: "New task", placeholder: "Add a task" },
    vendor: { label: "New vendor", placeholder: "Add a vendor" },
    guest: { label: "New guest", placeholder: "Add a guest" },
    side: "Side",
  },
  countdown: {
    unset: "Set the akad date",
    to: (n: number) => `${n === 1 ? "day" : "days"} to the akad`,
    since: (n: number) => `${n === 1 ? "day" : "days"} since the akad`,
    today: "The akad is today",
  },
  when: {
    today: "today",
    tomorrow: "tomorrow",
    in: (n: number) => `in ${plural(n, "day")}`,
    late: (n: number) => `${plural(n, "day")} late`,
    none: "No date",
  },
  route: {
    label: "Route to the akad",
    here: "You are here",
    allDone: (n: number) => `All ${n} done`,
    open: (n: number) => `${n} still open`,
    progress: (done: number, total: number) => `${done} of ${total} done`,
    tasks: (n: number) => plural(n, "task"),
    allTasks: "All tasks",
  },
  week: {
    heading: "Due soon and late",
    empty: "Nothing is due in the next 7 days.",
    overdue: "Late",
    soon: "Due soon",
    undated: "No date yet",
  },
  lately: {
    heading: "Lately",
    verb: { added: "added", ticked: "ticked off", paid: "paid", changed: "changed" },
  },
  money: {
    due: "due in the next 30 days",
    left: "left to pay",
    toPay: "To pay",
    byEvent: "By event",
    nothingToPay: "Nothing left to pay.",
    pick: "Pick a budget line to see its payments.",
    lineKind: "Budget line",
    estimatedOn: (estimated: number, lines: number) =>
      estimated === lines ? `estimated on ${plural(lines, "line")}.` : `estimated on ${estimated} of ${plural(lines, "line")}.`,
    paidSoFar: "paid,",
    leftToPay: "left.",
    noEstimates: "Nothing is estimated yet.",
  },
  empty: {
    task: "No tasks yet. Add the first one above.",
    vendor: "No vendors yet.",
    guest: "No guests yet.",
    budget: "No budget lines yet. Add the first one above.",
    payments: "No payments yet.",
  },
  budget: {
    planned: "Planned",
    paid: "Paid",
    remaining: "Remaining",
    over: "Over budget",
    unestimated: (n: number) => `${plural(n, "line")} ${n === 1 ? "is" : "are"} not estimated yet, so ${n === 1 ? "it is" : "they are"} not in these totals.`,
    notEstimated: (n: number) => `${n} not estimated`,
    notEstimatedLine: "Not estimated",
    paidOnUnestimated: "paid on lines without an estimate.",
    nothingPaid: "Nothing paid yet",
    paymentCount: (n: number) => plural(n, "payment"),
    progressNamed: (event: string) => `Paid of planned, ${event}`,
    addLabel: "New budget line",
    addPlaceholder: "Add a budget line",
    event: "Event",
    amountLabel: "Amount in rupiah",
    amountPlaceholder: "Amount",
    paidAmount: (amount: string) => `${amount} paid`,
    overBy: (amount: string) => `${amount} over`,
    left: (amount: string) => `${amount} left`,
    payments: "Payments",
    editLine: "Edit the line",
    addPayment: "Add a payment",
    paymentLabel: "Label (optional)",
  },
  contacts: {
    guests: "Guests",
    vendors: "Vendors",
    switch: "People",
    pick: "Pick a guest or a vendor to see the details.",
    guest: "Guest",
    vendor: "Vendor",
    noGroup: "No group",
    invitations: (n: number) => plural(n, "invitation"),
    vendorCount: (n: number) => plural(n, "vendor"),
    booked: (n: number) => `${n} booked`,
    noQuote: "No quote yet",
    noPhone: "No phone number yet.",
    edit: "Details",
    quote: "Quote",
  },
  notice: {
    reset: "The data on the server was reset, so this phone was reset to match.",
    discarded: (n: number) => `${plural(n, "change")} made on this phone could not be kept.`,
    dismiss: "Dismiss",
  },
  sync: {
    title: "Sync",
    synced: "All saved",
    storage: "Not saved on this phone",
    storageBody: "This phone could not store your latest change, so it was not kept. Free some space or allow site data for this page, then enter it again.",
    unknownRow: "A row that is no longer here",
    cleared: "cleared",
    yes: "yes",
    pending: "Saving",
    offline: (n: number) => (n > 0 ? "Offline, saved on this phone" : "Offline"),
    rejected: (n: number) => `${plural(n, "change")} ${n === 1 ? "needs" : "need"} a look`,
    login: "Log in again",
    onlineBody: "Connected. Changes are sent as soon as you make them.",
    offlineBody: "The server cannot be reached. Everything you enter is saved on this phone and sent later.",
    expiredBody: "Your login expired. Log in again to send your changes. Nothing is lost.",
    waiting: (n: number) => (n === 0 ? "Nothing waiting to sync." : `${n} ${n === 1 ? "change is" : "changes are"} waiting to sync.`),
    now: "Sync now",
    attention: "Needs attention",
    attentionBody: "The server refused these changes. They are not applied. Discard them and enter them again if you still need them.",
    discard: "Discard",
    op: { create: "New", update: "Change to", delete: "Delete" },
    table: { items: "item", budget_entries: "budget entry", settings: "setting" },
  },
  settings: {
    day: "The day",
    two: "The two of you",
    look: "Look",
    data: "Your data",
    ceremonyDate: "Akad date (marriage contract ceremony)",
    ceremonyShort: "Akad",
    timezone: "Time zone",
    zoneUnsupported: "This phone does not support the saved time zone, so dates use the default zone. You can still edit it.",
    yourNickname: "Your nickname",
    theirNickname: "Their nickname",
    youSignedIn: "You are signed in",
    signedInAs: (name: string) => `You are signed in as ${name}.`,
    notSet: "Not set",
    zoneInvalid: "Use a time zone such as Asia/Jakarta.",
    noEmpty: "A setting cannot be left empty. Cancel to keep the old one.",
    noNickname: "No nickname yet",
    what: { date: "the akad date", zone: "the time zone", mine: "your nickname", theirs: "their nickname" },
    change: (what: string) => `Change ${what}`,
    cancel: (what: string) => `Cancel changing ${what}`,
    save: (what: string) => `Save ${what}`,
    nicknamesNote: "Nicknames show instead of You and Them, and they are read in quick add.",
    hijriLabel: "Hijri date",
    hijriNote: "Umm al-Qura calendar. It can differ by a day from local announcements, so adjust it here if yours does.",
    hijriUnavailable: "This browser cannot show Hijri dates.",
    hijriAdjust: "Adjust the Hijri date",
    hijriOffset: { "-1": "A day earlier", "0": "As calculated", "1": "A day later" },
    lookLabel: "Appearance",
    lookNote: "Kept on this device only.",
    theme: { system: "Match this device", light: "Light", dark: "Dark" },
    export: "Export",
    exportAll: "Everything (JSON)",
    exportBody: "Everything here is shared by both of you.",
    syncDetails: "Sync details",
    signOut: "Sign out",
    signOutNote: "Signs you out of this browser only.",
  },
  stages: {
    heading: "Route stages",
    intro: "The stops on the route to the akad. Each one covers some months around the akad month.",
    count: (n: number) => (n === 1 ? "1 stage" : `${n} stages`),
    full: "That is the most stages, or the last month, the route can have.",
    changed: "Not saved yet",
    name: "Name",
    from: "From",
    to: "To",
    nameOf: (n: number) => `Name of stage ${n}`,
    fromOf: (n: number) => `From, stage ${n}`,
    toOf: (n: number) => `To, stage ${n}`,
    stage: (n: number, name = "") => `Stage ${n}: ${name.trim() === "" ? "no name yet" : name}`,
    up: (name: string) => `Move ${name} up`,
    down: (name: string) => `Move ${name} down`,
    remove: (name: string) => `Remove ${name}`,
    add: "Add a stage",
    reset: "Reset to the default stages",
    save: "Save stages",
    saved: "Stages saved",
    unsaved: "Not saved yet",
    renameNote: "Renaming a stage does not rename the phase on tasks that already use it.",
    month: (offset: number, label: string | null = null) =>
      `${label === null ? "" : `${label} · `}${offset === 0 ? "the akad month" : offset < 0 ? `${-offset} ${offset === -1 ? "month" : "months"} before` : `${offset} ${offset === 1 ? "month" : "months"} after`}`,
    problem: {
      count: "Keep between 1 and 12 stages.",
      shape: "This stage is not readable. Remove it and add it again.",
      key: "This stage has no valid key. Remove it and add it again.",
      key_twice: "Two stages share a key. Remove one and add it again.",
      name: "Give the stage a name of up to 40 characters.",
      name_twice: "Another stage already has this name.",
      range: "The end cannot be before the start.",
      bounds: "Pick a month from 36 months before to 12 months after the akad.",
      overlap: "This stage must start after the one before it ends.",
    },
  },
  export: {
    task: "Tasks (CSV)",
    vendor: "Vendors (CSV)",
    guest: "Guests (CSV)",
    planned: "Budget lines (CSV)",
    payment: "Payments (CSV)",
  },
  signIn: {
    title: "Sign in to continue",
    body: "This plan is private. Only the two Google accounts it was made for can open it.",
    action: "Continue with Google",
    note: "Google handles the sign-in. wp never sees your password.",
  },
  denied: {
    title: "Wrong Google account",
    body: "This Google account cannot open this plan. Sign in with the account you use for wp.",
    action: "Try another account",
  },
  sheet: {
    title: "Add",
    close: "Close",
    kind: "Kind",
    kinds: { task: "Task", planned: "Budget line", payment: "Payment", guest: "Guest", vendor: "Vendor" },
    first: { task: "Task", planned: "Budget line", payment: "Payment", guest: "Guest", vendor: "Vendor" },
    placeholder: {
      task: "Book the venue visit Friday",
      planned: "Photography 12 jt",
      payment: "Venue deposit 5 jt Friday",
      guest: "Neighbour 0812 3456 7890",
      vendor: "Florist 0812 3456 7890",
    },
    savedAs: (title: string) => `Saved as “${title}”`,
    chips: "Read from your text",
    chipsEmpty: "Details",
    putBack: "Put the words back in the name",
    owner: { task: "Who does it?", payment: "Who pays?", guest: "Which side?" },
    detail: { amount: "Amount", due: "Due date", line: "Budget line", phone: "Phone", qty: "People" },
    group: { task: "Phase", planned: "Event", vendor: "Category", guest: "Category" },
    none: { amount: "No amount", due: "No date", line: "Choose a line", phone: "No phone", group: "None", qty: "1 person" },
    ownerRead: (name: string) => `Owner read from the word ${name}`,
    need: {
      name: "Add a name.",
      amount: "Add an amount.",
      line: "Choose a budget line.",
      noLines: "Add a budget line first, then its payments.",
      qty: "Enter a number of people, 1 or more.",
    },
    save: { task: "Add task", planned: "Add budget line", payment: "Add payment", guest: "Add guest", vendor: "Add vendor" },
    hint: "Only the first line is needed. Dates, amounts and names are read from it. Tap a chip to fix one. What you type is kept until you add it.",
    added: (title: string) => `Added: ${title}`,
  },
  capture: {
    label: "Add something",
    placeholder: "Add something",
    go: "Add",
    review: "Review and add",
  },
  connect: {
    title: "Can't reach the server yet",
    body: "This phone has not loaded your plan yet. Check your connection and try again. Nothing is created until the plan has loaded once.",
    retry: "Try again",
  },
};
